AllCops:
  Exclude:
    - 'bin/**'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 80

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context"]

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
